services:
  laravel-docker:
    container_name: laravel-docker
    build: ./
    ports:
      - 8000:80
    volumes: 
      - ./:/var/www/html
    working_dir: /var/www/html

  tattooartist_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: //T4tt00Artist//
      MYSQL_DATABASE: tattooartist
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      PMA_HOST: tattooartist_db